TITLE:
[CLI] Syncing all offline runs using `wandb sync --sync-all`

LABEL:
cli

STATE:
closed

BODY:
**Description**
When I run `wandb sync --sync-all --include-synced` I get the following error: `wandb: ERROR Nothing to sync.`.

**Wandb features**
I am using `wandb sync` in the CLI, and `wandb.init` as well as the `WandbCallback` for keras training.

**How to reproduce**
1. Link to a reproducible script we can run to see the bug
Unfortunately I can't link the script and I don't have a minimal reproducible example just yet.
2. Describe what we have to do in order to trigger the issue
I guess just running wandb offline and trying `wandb sync --sync-all --include-synced` in the runs directory.
3. Add a zip file with the run folder 
It's more than 1 run: should I still add it here?
One of the runs' logs are available [here](https://github.com/wandb/client/issues/1297#issuecomment-1005754497).

**Environment**
- OS: RedHat version 8.1
- Python Version: 3.7.9

**Misc**
I had another error with offline post-sync, I reported it [here](https://github.com/wandb/client/issues/1297#issuecomment-1004936577), and managed to solve it by basically repeatedly using `wandb sync`, but it didn't work with `wandb sync --sync-all`.


