TITLE:
[CLI]: passing a list of tags to `Api.runs()` causes a server-side 500 Error

LABEL:
cli

STATE:
closed

BODY:
### Describe the bug

<!--- Description of the issue below  -->
When naively attempting to pass a list of tags as filters to the `Api.runs()` method, a server-side error occurs. The resulting stack trace is not very informative and does not point the user in the right direction (i.e. passing a single tag and using `$or` and supposedly `$and` to specify multiple ones). This is particularly confusing since: 1) the key is `tags` (plural); 2) the documentation doesn't show examples on how to filter by tags.
I suggest you perform some client-side validation and either raise a more informative error or automatically convert the list into whatever syntax is accepted by the server-side.

<!--- A minimal code snippet between the quotes below  -->
```python
api = wandb.Api()
api.runs('entity/project', filters={'tags': ['train']})
```

<!--- A full traceback of the exception in the quotes below -->
```shell

Retry attempt failed:
Traceback (most recent call last):
  File "/home/rmiccini/miniconda3/envs/speakerid_training/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rmiccini/miniconda3/envs/speakerid_training/lib/python3.9/site-packages/wandb/apis/public.py", line 205, in execute
    return self._client.execute(*args, **kwargs)
  File "/home/rmiccini/miniconda3/envs/speakerid_training/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/rmiccini/miniconda3/envs/speakerid_training/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/rmiccini/miniconda3/envs/speakerid_training/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/rmiccini/miniconda3/envs/speakerid_training/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
wandb: Network error (HTTPError), entering retry loop.
```


### Additional Files

_No response_

### Environment

WandB version: 0.12.16

OS: Ubuntu 22.04 LTS

Python version: 3.9.12

Versions of relevant libraries: N/A


### Additional Context

_No response_

