TITLE:
[Q] Getting ` 'NoneType' object has no attribute '_log'` when trying to use test_set after training and logging resuls with wandb

LABEL:
c:misc

STATE:
closed

BODY:
Once, I finish my training and log-off all the results to wandb (I think wandb calls finish implicitly here), I try to use my test_set to see how my model performs 
```python
def test(model, test_loader):
    model.eval()

    # Run the model on some test examples
    with torch.no_grad():
        correct, total = 0, 0
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        print(f"Accuracy of the model on the {total} " +
              f"test images: {correct / total:%}")
       
test(model_ft,dataloaders[TEST] )
```
But when i call my function test, it return AttributeError
```bash
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

[<ipython-input-47-bb2d2c388fbd>](https://localhost:8080/#) in <module>
----> 1 test(model_ft,dataloaders[TEST] )

4 frames

[/usr/local/lib/python3.7/dist-packages/wandb/wandb_torch.py](https://localhost:8080/#) in log_tensor_stats(self, tensor, name)
    254             bins = torch.Tensor(bins_np)
    255 
--> 256         wandb.run._log(
    257             {name: wandb.Histogram(np_histogram=(tensor.tolist(), bins.tolist()))},
    258             commit=False,

AttributeError: 'NoneType' object has no attribute '_log'
```

Should I test my model before wandb calls finish implicitly ?

