TITLE:
[CLI]: Sync raises KeyError: 'step'

LABEL:
cli

STATE:
closed

BODY:
### Describe the bug

<!--- Description of the issue below  -->

<!--- A minimal code snippet between the quotes below  -->
```python

# one line command
WandbLogger.sync()

# passing optional parameters
WandbLogger.sync(
    id=None,
    n_fine_tunes=None,
    project="gpt-3",
    **kwargs_wandb_init
)


```

<!--- A full traceback of the exception in the quotes below -->
```shell

KeyError                                  Traceback (most recent call last)
Input In [283], in <cell line: 4>()
      1 # THIS IS TO SYNC ALL THE PAST TO WANDB 
      2 
      3 # one line command
----> 4 WandbLogger.sync()
      6 # passing optional parameters
      7 WandbLogger.sync(
      8     id=None,
      9     n_fine_tunes=None,
     10     project="gpt-3",
     11     **kwargs_wandb_init
     12 )

File ~/opt/anaconda3/lib/python3.9/site-packages/openai/wandb_logger.py:73, in WandbLogger.sync(cls, id, n_fine_tunes, project, entity, force, **kwargs_wandb_init)
     69 # log starting from oldest fine_tune
     70 show_individual_warnings = (
     71     False if id is None and n_fine_tunes is None else True
     72 )
---> 73 fine_tune_logged = [
     74     cls._log_fine_tune(
     75         fine_tune,
     76         project,
     77         entity,
     78         force,
     79         show_individual_warnings,
     80         **kwargs_wandb_init,
     81     )
     82     for fine_tune in fine_tunes
     83 ]
     85 if not show_individual_warnings and not any(fine_tune_logged):
     86     print("No new successful fine-tunes were found")

File ~/opt/anaconda3/lib/python3.9/site-packages/openai/wandb_logger.py:74, in <listcomp>(.0)
     69 # log starting from oldest fine_tune
     70 show_individual_warnings = (
     71     False if id is None and n_fine_tunes is None else True
     72 )
     73 fine_tune_logged = [
---> 74     cls._log_fine_tune(
     75         fine_tune,
     76         project,
     77         entity,
     78         force,
     79         show_individual_warnings,
     80         **kwargs_wandb_init,
     81     )
     82     for fine_tune in fine_tunes
     83 ]
     85 if not show_individual_warnings and not any(fine_tune_logged):
     86     print("No new successful fine-tunes were found")

File ~/opt/anaconda3/lib/python3.9/site-packages/openai/wandb_logger.py:162, in WandbLogger._log_fine_tune(cls, fine_tune, project, entity, force, show_individual_warnings, **kwargs_wandb_init)
    160 for _, row in df_results.iterrows():
    161     metrics = {k: v for k, v in row.items() if not np.isnan(v)}
--> 162     step = metrics.pop("step")
    163     if step is not None:
    164         step = int(step)

KeyError: 'step'

```


### Additional Files

_No response_

### Environment

WandB version:  0.13.9

OS: MacOS

Python version: 3.10

Versions of relevant libraries:

openai                        0.26.3

### Additional Context

_No response_

