TITLE:
[App]: Cannot open files in the UI for the runs created with a group specified

LABEL:
app

STATE:
open

BODY:
### Current Behavior

If I create the run with the group specified (`run = wandb.init(project='my-awesome-project', config=model_params, group="my-run-group")`), then I cannot open any file in the "Files" section in the UI.

If my run doesn't belong to any group, the files open just fine.

I see the same incorrect behaviour on both W&B cloud and when running W&B locally using `wandb/local:latest` docker image.

### Expected Behavior

I expect to be able to explore the run files regardless of whether a group was specified or not.

### Steps To Reproduce

1. Create a run with the group `run = wandb.init(project='my-awesome-project', config=model_params, group="my-run-group")`
2. Go to wandb.ai
3. Navigate to Projects / my-awesome-project / Runs / <your run name>
4. Open "Files" tab
5. Click on any file

### Screenshots

Trying to open `conda-environment.yaml` for the run with the group:

![image](https://user-images.githubusercontent.com/34062032/221354404-605723f0-9b06-4aea-bdfa-9e773c5cbeeb.png)

Trying to open `conda-environment.yaml` for the run without a group (note the URL difference with the first screenshot):
![image](https://user-images.githubusercontent.com/34062032/221354461-2db958f9-1aff-4b84-930e-6a16f23c0896.png)


### Environment

OS: Ubuntu 20.04.5 LTS

Browsers: Chrome Version 104.0.5112.101 (Official Build) (64-bit)

Version:


### Additional Context

_No response_

