TITLE:
Resuming specific run fails with no error

LABEL:
bug,stale

STATE:
closed

BODY:
* Weights and Biases version: 0.8.14
* Python version: 3.6.9
* Operating System: Debian 10

### Description
When I try to resume a specific run like this:
```python
import wandb
wandb.init(resume=True, id='08heesh9')
```
The init call returns, but a moment later a `KeyboardInterrupt` is raised, which I guess means an exception happened somewhere in a different thread. Resuming a different run in the same way works fine. There is no error output and looking at `wandb/debug.log` there doesn't seem to be anything out of the usual:
```
2019-11-04 11:16:42,433 DEBUG   MainThread:25226 [wandb_config.py:_load_defaults():108] no defaults not found in config-defaults.yaml
2019-11-04 11:16:42,449 DEBUG   MainThread:25226 [git_repo.py:repo():30] git repository is invalid
2019-11-04 11:16:42,458 DEBUG   MainThread:25226 [run_manager.py:__init__():535] Initialized sync for thesis/08heesh9
2019-11-04 11:16:42,461 INFO    MainThread:25226 [run_manager.py:wrap_existing_process():1131] wrapping existing process 24977
2019-11-04 11:16:42,462 WARNING MainThread:25226 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2019-11-04 11:16:42,466 DEBUG   MainThread:25226 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): pypi.org:443
2019-11-04 11:16:42,567 DEBUG   MainThread:25226 [connectionpool.py:_make_request():396] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 37397
2019-11-04 11:16:42,587 INFO    MainThread:25226 [run_manager.py:init_run():916] system metrics and metadata threads started
2019-11-04 11:16:42,587 INFO    MainThread:25226 [run_manager.py:init_run():925] checking resume status, waiting at most 10 seconds
2019-11-04 11:16:42,593 DEBUG   Thread-14 :25226 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-04 11:16:42,897 DEBUG   Thread-14 :25226 [connectionpool.py:_make_request():396] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2019-11-04 11:16:42,943 INFO    MainThread:25226 [run_manager.py:init_run():938] resuming run from id: UnVuOnYxOjA4aGVlc2g5OnRoZXNpczpkbXJ0em4=
2019-11-04 11:16:42,965 INFO    MainThread:25226 [run_manager.py:init_run():950] upserting run before process can begin, waiting at most 10 seconds
2019-11-04 11:16:42,977 DEBUG   Thread-17 :25226 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-04 11:16:43,177 DEBUG   Thread-17 :25226 [connectionpool.py:_make_request():396] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 526
2019-11-04 11:16:43,189 INFO    Thread-17 :25226 [run_manager.py:_upsert_run():1035] saving patches
2019-11-04 11:16:43,190 INFO    Thread-17 :25226 [run_manager.py:_upsert_run():1039] saving pip packages
2019-11-04 11:16:43,192 INFO    Thread-17 :25226 [run_manager.py:_upsert_run():1041] initializing streaming files api
2019-11-04 11:16:43,192 INFO    Thread-17 :25226 [run_manager.py:_upsert_run():1048] unblocking file change observer, beginning sync with W&B servers
2019-11-04 11:16:43,193 INFO    MainThread:25226 [run_manager.py:wrap_existing_process():1148] informing user process we are ready to proceed
2019-11-04 11:16:43,198 INFO    MainThread:25226 [run_manager.py:_sync_etc():1255] entering loop for messages from user process
2019-11-04 11:16:43,199 DEBUG   Thread-18 :25226 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-04 11:16:43,359 DEBUG   Thread-18 :25226 [connectionpool.py:_make_request():396] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 45
2019-11-04 11:16:43,447 INFO    Thread-3  :25226 [run_manager.py:_on_file_modified():682] file/dir modified: /home/user/mouritzen/thesis2/wandb/run-20191104_101641-08heesh9/wandb-history.jsonl
2019-11-04 11:16:43,448 INFO    Thread-3  :25226 [run_manager.py:_on_file_modified():682] file/dir modified: /home/user/mouritzen/thesis2/wandb/run-20191104_101641-08heesh9/config.yaml
2019-11-04 11:16:43,459 DEBUG   Thread-3  :25226 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-04 11:16:43,759 DEBUG   Thread-3  :25226 [connectionpool.py:_make_request():396] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 548
2019-11-04 11:16:43,766 INFO    Thread-3  :25226 [run_manager.py:_on_file_created():671] file/dir created: /home/user/mouritzen/thesis2/wandb/run-20191104_101641-08heesh9/wandb-metadata.json
2019-11-04 11:16:43,766 INFO    Thread-3  :25226 [run_manager.py:_on_file_created():671] file/dir created: /home/user/mouritzen/thesis2/wandb/run-20191104_101641-08heesh9/output.log
2019-11-04 11:16:43,767 INFO    Thread-3  :25226 [run_manager.py:_on_file_created():671] file/dir created: /home/user/mouritzen/thesis2/wandb/run-20191104_101641-08heesh9/requirements.txt
2019-11-04 11:16:43,767 INFO    Thread-3  :25226 [run_manager.py:_on_file_created():671] file/dir created: /home/user/mouritzen/thesis2/wandb/run-20191104_101641-08heesh9/wandb-events.jsonl
2019-11-04 11:16:43,768 ERROR   Thread-3  :25226 [run_manager.py:on_created():320] Streaming file created twice in same run: /home/user/mouritzen/thesis2/wandb/run-20191104_101641-08heesh9/wandb-events.jsonl
2019-11-04 11:16:43,768 INFO    Thread-3  :25226 [run_manager.py:_on_file_created():671] file/dir created: /home/user/mouritzen/thesis2/wandb/run-20191104_101641-08heesh9/wandb-summary.json
2019-11-04 11:16:45,455 DEBUG   Thread-19 :25226 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-04 11:16:45,556 DEBUG   Thread-20 :25226 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-04 11:16:45,623 DEBUG   Thread-19 :25226 [connectionpool.py:_make_request():396] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 760
2019-11-04 11:16:45,631 DEBUG   Thread-19 :25226 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): storage.googleapis.com:443
2019-11-04 11:16:45,655 DEBUG   Thread-21 :25226 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-04 11:16:45,725 DEBUG   Thread-20 :25226 [connectionpool.py:_make_request():396] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 774
2019-11-04 11:16:45,731 DEBUG   Thread-20 :25226 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): storage.googleapis.com:443
2019-11-04 11:16:45,773 DEBUG   Thread-7  :25226 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-04 11:16:45,826 DEBUG   Thread-21 :25226 [connectionpool.py:_make_request():396] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 766
2019-11-04 11:16:45,834 DEBUG   Thread-21 :25226 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): storage.googleapis.com:443
2019-11-04 11:16:45,985 DEBUG   Thread-7  :25226 [connectionpool.py:_make_request():396] https://api.wandb.ai:443 "POST /files/dmrtzn/thesis/08heesh9/file_stream HTTP/1.1" 200 311
2019-11-04 11:16:46,021 DEBUG   Thread-19 :25226 [connectionpool.py:_make_request():396] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/dmrtzn/thesis/08heesh9/config.yaml?Expires=1572862665&GoogleAccessId=gorilla-cloud-storage%40wandb-production.iam.gserviceaccount.com&Signature=IhIblapss3oC418NCvCojTAhP%2FtD7mNZOYpuSdi7o5BO2yyunwEXzwq1emWsAVhij%2BWvhPqdTOm45VmT7UsGjwGmWSJtJxRAqD1THjninr6U8R8uIzboD%2BNqR05GoQvqVmibz55ZjjpY8NRXM55Ydg975o1Q16LLr8bUHyscZt6SEvzIWqAd%2FCgEaKX8W5k%2B0H4tmD6b2G0NKQ7MUu3NrqsIF17kuQs1Ozg5%2FixoB%2BGPB3dtGx3foTlu%2FQZ7gC4iux0F%2F6B8Xq5y7vxrh%2FefqHt2b40%2FQCCoOE4ItAmIYw9OETlwiUVAwlWHcnYebTgkWMxKE3H6Cf%2B4NccsmjncUw%3D%3D HTTP/1.1" 200 0
2019-11-04 11:16:46,093 DEBUG   Thread-20 :25226 [connectionpool.py:_make_request():396] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/dmrtzn/thesis/08heesh9/wandb-metadata.json?Expires=1572862665&GoogleAccessId=gorilla-cloud-storage%40wandb-production.iam.gserviceaccount.com&Signature=jz6nB%2BAXtigEHOIgbolGirsi51JRKzKR9FjcPmlvxBEWly8nRAXjvEEw3GUaW1wAWrdG1NjmPRG5JfgSdqaC7sVGUPcAcv8coCQ4MvLCcWGfbv%2F9y%2Bwoo3p0iADYFdQfbf59%2FmVjOS0eFI5WEkMsC%2FDGBgOZEk0V80f297Ikp9WVkxwqx35t0%2BC9Ixbpf1h9JNmpuiH2nv1ty0QY4ATQQ3dWQXLS6ci05fUtIgk2cUczTiBGaTWmREWEtkiq8Pa9N3wv%2BjbD2%2B3Sws%2BPhxsNleGARZ9vIcTIwsJ2fA4GFP37LiY5v8qn1oqjS15ZRvvlai%2FHzqhzAAkGieST%2FKYaCQ%3D%3D HTTP/1.1" 200 0
2019-11-04 11:16:46,150 DEBUG   Thread-21 :25226 [connectionpool.py:_make_request():396] https://storage.googleapis.com:443 "PUT /wandb-production.appspot.com/dmrtzn/thesis/08heesh9/requirements.txt?Expires=1572862665&GoogleAccessId=gorilla-cloud-storage%40wandb-production.iam.gserviceaccount.com&Signature=a5g%2FwFYuhdn1aBCkn0YWiUTzpRS%2Fpn846%2F538H9lb%2BMP%2BehuDkZJZqXf2Cfeqn0gI1WbP0Nb0Go4VtJimFwTXrPr6pvjWh6UNV07hfHluDAUt93kKHiiLvmA7EJiujxA8EFNtizWc2kEI6qJ0OUnBeTYAVCpCCptcYP2wWH77DekGp5XxH85d6xpEh1pqlCHfbte%2Frabwd9ONFcnvzRZ5Dwd7Qit0Ncl0YV%2BOTmywNPCjzdmEonxjd%2F4CObBCd54q6%2BGaqe3t2yXGzINXLpWy8n8owqt2tqcMGXn5NhROl3GidNguB1v71kbc449uDrNxHYzMGp%2BKwgnhmY8QZmP7w%3D%3D HTTP/1.1" 200 0
2019-11-04 11:16:47,204 INFO    MainThread:25226 [run_manager.py:_sync_etc():1278] received message from user process: {"exitcode": 255}
2019-11-04 11:16:47,204 INFO    MainThread:25226 [run_manager.py:_sync_etc():1364] closing log streams and sending exitcode to W&B
2019-11-04 11:16:47,206 INFO    MainThread:25226 [run_manager.py:shutdown():1055] shutting down system stats and metadata service
2019-11-04 11:16:47,451 INFO    Thread-3  :25226 [run_manager.py:_on_file_modified():682] file/dir modified: /home/user/mouritzen/thesis2/wandb/run-20191104_101641-08heesh9/wandb-events.jsonl
2019-11-04 11:16:47,451 INFO    Thread-3  :25226 [run_manager.py:_on_file_modified():682] file/dir modified: /home/user/mouritzen/thesis2/wandb/run-20191104_101641-08heesh9/output.log
2019-11-04 11:16:47,595 INFO    MainThread:25226 [run_manager.py:shutdown():1067] stopping streaming files and file change observer
2019-11-04 11:16:48,154 DEBUG   Thread-7  :25226 [connectionpool.py:_make_request():396] https://api.wandb.ai:443 "POST /files/dmrtzn/thesis/08heesh9/file_stream HTTP/1.1" 200 311
2019-11-04 11:16:48,453 INFO    MainThread:25226 [run_manager.py:_on_file_modified():682] file/dir modified: /home/user/mouritzen/thesis2/wandb/run-20191104_101641-08heesh9/wandb-metadata.json
2019-11-04 11:16:48,985 DEBUG   MainThread:25226 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-04 11:16:49,183 DEBUG   MainThread:25226 [connectionpool.py:_make_request():396] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 548
2019-11-04 11:16:49,217 DEBUG   Thread-22 :25226 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): api.wandb.ai:443
2019-11-04 11:16:49,387 DEBUG   Thread-22 :25226 [connectionpool.py:_make_request():396] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 761
2019-11-04 11:16:49,394 DEBUG   Thread-22 :25226 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): storage.googleapis.com:443
2019-11-04 11:16:49,398 DEBUG   Thread-7  :25226 [connectionpool.py:_make_request():396] https://api.wandb.ai:443 "POST /files/dmrtzn/thesis/08heesh9/file_stream HTTP/1.1" 200 311
2019-11-04 11:16:49,565 DEBUG   Thread-7  :25226 [connectionpool.py:_make_request():396] https://api.wandb.ai:443 "POST /files/dmrtzn/thesis/08heesh9/file_stream HTTP/1.1" 200 310
2019-11-04 11:16:49,566 INFO    MainThread:25226 [run_manager.py:_sync_etc():1376] process only ran for 7 seconds, not syncing files
2019-11-04 11:16:49,566 INFO    MainThread:25226 [08heesh9:run_manager.py:_sync_etc():1376] process only ran for 7 seconds, not syncing files
```

I compared with the log after a successful resume and it looks exactly the same until the last two lines (including the error related to `wandb-events.jsonl`, so I guess that's not related).

Any idea what's going on?

