TITLE:
[CLI] ValueError: check_hostname requires server_hostname

LABEL:
c:misc

STATE:
closed

BODY:
**Question: I created a new Python environment and installed wandb, but I can't even run a simple script.**. I have tested this script on colab and it works fine. Please let me know if I missed something. Thank you.

```python
import wandb
run = wandb.init(project="runs-from-for-loop")
for x in range(10):
    wandb.log({"metric": x})
```
**log:**
```
wandb: W&B API key is configured (use `wandb login --relogin` to force relogin)
Thread SenderThread:
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\apis\normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\sdk\internal\internal_api.py", line 883, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\old\retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\sdk\internal\internal_api.py", line 123, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\vendor\gql-0.2.0\gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\sdk\internal\internal_util.py", line 54, in run
    self._run()
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\sdk\internal\internal_util.py", line 95, in _run
    self._process(record)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\sdk\internal\internal.py", line 279, in _process
    self._sm.send(record)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\sdk\internal\sender.py", line 162, in send
    send_handler(record)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\sdk\internal\sender.py", line 541, in send_run
    self._init_run(run, config_value_dict)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\sdk\internal\sender.py", line 563, in _init_run
    server_run, inserted = self._api.upsert_run(
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\apis\normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\apis\normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\sdk\internal\internal_api.py", line 883, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\old\retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\sdk\internal\internal_api.py", line 123, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\vendor\gql-0.2.0\gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
wandb.errors.CommError: check_hostname requires server_hostname
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\hilonet_for_optical_sectioning\boring_test.py", line 2, in <module>
    run = wandb.init(project="runs-from-for-loop")
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\sdk\wandb_init.py", line 745, in init
    run = wi.init()
  File "C:\Users\Administrator\anaconda3\envs\ss\lib\site-packages\wandb\sdk\wandb_init.py", line 513, in init
    raise UsageError(error_message)
wandb.errors.UsageError: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
Problem at: C:\Users\Administrator\PycharmProjects\hilonet_for_optical_sectioning\boring_test.py 2 <module>
```
**my env(from pycharm)**
``` 
ca-certificates | 2021.1.19 | 2021.1.19
certifi | 2020.12.5 | 2020.12.5
chardet | 4.0.0 | 4.0.0
click | 7.1.2 | 7.1.2
configparser | 5.0.2 | 5.0.2
docker-pycreds | 0.4.0 | 0.4.0
gitdb | 4.0.7 | 4.0.5
gitpython | 3.1.14 | 3.1.14
idna | 2.10 | 3.1
openssl | 1.1.1k | 1.1.1k
pathtools | 0.1.2 | 0.1.2
pip | 21.0.1 | 21.0.1
promise | 2.3 | 2.3
protobuf | 3.15.6 | 3.14.0
psutil | 5.8.0 | 5.8.0
python | 3.9.2 | 3.9.2
python-dateutil | 2.8.1 | 2.8.1
pyyaml | 5.4.1 | 5.4.1
requests | 2.25.1 | 2.25.1
sentry-sdk | 1.0.0 |  
setuptools | 52.0.0 | 52.0.0
shortuuid | 1.0.1 |  
six | 1.15.0 | 1.15.0
smmap | 4.0.0 | 4.0.0
sqlite | 3.35.2 | 3.35.2
subprocess32 | 3.5.4 | 3.5.4
tzdata | 2020f | 2020f
urllib3 | 1.26.4 | 1.26.4
vc | 14.2 | 14.2
vs2015_runtime | 14.27.29016 | 14.27.29016
wandb | 0.10.23 |  
wheel | 0.36.2 | 0.36.2
wincertstore | 0.2 | 0.2
```

