TITLE:
[Q] Getting `OSError: [Errno 28] No space left on device:` when uploading artifact 

LABEL:
c:misc

STATE:
closed

BODY:
I'm not sure if this is a bug or question, but I'm getting this bug when trying to upload my dataset: `OSError: [Errno 28] No space left on device:`. This seems to be caused by the `../cache/.wandb`, which gets populated during the upload. I currently manually delete the folder, then run my upload script again. 

My question is if I continue to do this (delete cache folder and attempt to re-upload), will the artifact eventually get uploaded, or is it getting reset each time? 

My device has ~470 GB total, but my dataset is ~510 GB. I have ~300 GB to upload since my last artifact version. 

Full stack trace: 
```
  File "Dataset/upload_dataset.py", line 45, in <module>
    upload_dataset()
  File "Dataset/upload_dataset.py", line 24, in upload_dataset
    dataset.add_dir(vid_dir)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 419, in add_dir
    pool.map(add_manifest_file, paths)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 413, in add_manifest_file
    self._add_local_file(logical_path, physical_path)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 696, in _add_local_file
    shutil.copyfile(path, f.name)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/shutil.py", line 275, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/shutil.py", line 166, in _fastcopy_sendfile
    raise err from None
  File "/home/wilsonchan/anaconda3/envs/AceOne-CALF/lib/python3.8/shutil.py", line 152, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 28] No space left on device: './Dataset/BWF TV/20210126-20210131 HSBC BWF World Tour Finals 2020/[Flipped] 20210130 - HSBC BWF World Tour Finals _ Day 4 - Seo_Chae (KOR) vs. Goh_Lai (
MAS)/[Flipped] 20210130 - HSBC BWF World Tour Finals _ Day 4 - Seo_Chae (KOR) vs. Goh_Lai (MAS).mp4' -> '/home/wilsonchan/.cache/wandb/artifacts/obj/md5/14/tmp_BA5EE0BD'
```

