TITLE:
Process hangs due to race condition in file pusher?

LABEL:
cli

STATE:
closed

BODY:
### Describe the bug

Our team has been using the `wandb` logger in `pytorch-lightning` to monitor trial progress and log artifacts for over a year now and fairly recently (perhaps due to recent upgrades of our `wandb` version?) we've been encountering a bug where upon the completion of a trial, the process hangs, seemingly due to a race condition in file uploading. Our `debug-internal.log` file ends with the following 3 lines: 
```
2022-10-16 08:04:19,712 INFO    SenderThread:615 [sender.py:finish():1315] shutting down sender
2022-10-16 08:04:19,712 INFO    SenderThread:615 [file_pusher.py:finish():168] shutting down file pusher
2022-10-16 08:04:19,713 INFO    SenderThread:615 [file_pusher.py:join():173] waiting for file pusher
```
At face value, this would appear to be a race condition of some kind. Worth noting perhaps is the fact that we are using a `tempfile.TemporaryDirectory` as our `save_dir`. Also worth mentioning is the potential relatedness of #269.

Please let me know if I can provide any more details regarding the nature of the issue. We're currently in the process of decrementing our `wandb` version in the hopes that this will help but currently, this issue is blocking our ability to use `wandb`!

### Additional Files

_No response_

### Environment

WandB version: 0.13.3

OS: ubuntu 18.04

Python version: 3.8.10


### Additional Context

_No response_

